spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/password-manager?currentSchema=public&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000
      pool-name: HikariCP
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
jwt:
  secret: aVeryLongAndSecureSecretKeyForMyPasswordManagerApplicationThatNobodyShouldGuess
  expiration: 3600000


