spring:
  application:
    name: password-manager
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root