###
# Vault Items API
###

### Create a new vault item
# @name createVaultItem
POST {{host}}/{{api.path}}/{{api.version}}/vault/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Gmail Account",
  "resource": "https://mail.google.com",
  "description": "Personal Gmail account.",
  "login": "my.email@gmail.com",
  "password": "MySecretPassword123!",
  "collection": {
    "id": 2
  }
}

### Create a new vault item and assign it to a collection
# @name createVaultItemInCollection
POST {{host}}/{{api.path}}/{{api.version}}/vault/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Facebook Account",
  "resource": "https://www.facebook.com",
  "description": "Personal Facebook account.",
  "login": "my.email@gmail.com",
  "password": "AnotherSecretPassword456!",
  "collection": {
    "id": 1
  }
}


###
POST {{host}}/{{api.path}}/{{api.version}}/vault/import
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[
  {
    "name": "Import 1",
    "resource": "test-resource.com",
    "description": "Test description",
    "login": "test@gmail.com",
    "password": "testPassword",
    "collection": {
      "id": 2
    }
  },
  {
    "name": "Import 2",
    "resource": "test-resource.com",
    "description": "Test description",
    "login": "",
    "password": "testPassword",
    "collection": {
      "id": 2
    }
  }
]

###
GET {{host}}/{{api.path}}/{{api.version}}/vault/all
Authorization: Bearer {{auth_token}}

### Get all vault items
# @name getAllVaultItems
GET {{host}}/{{api.path}}/{{api.version}}/vault/all
Authorization: Bearer {{auth_token}}

### Get vault item by ID
# @name getVaultItemById
GET {{host}}/{{api.path}}/{{api.version}}/vault/1
Authorization: Bearer {{auth_token}}

### Find by login
# @name findVaultItemByLogin
GET {{host}}/{{api.path}}/{{api.version}}/vault/login/my.email@gmail.com
Authorization: Bearer {{auth_token}}

### Find by resource
# @name findVaultItemByResource
GET {{host}}/{{api.path}}/{{api.version}}/vault/resource?resource=https://mail.google.com
Authorization: Bearer {{auth_token}}

###Find by collection
GET {{host}}/{{api.path}}/{{api.version}}/vault/collection/Social Media
Authorization: Bearer {{auth_token}}

### Update a vault item
# @name updateVaultItem
PUT {{host}}/{{api.path}}/{{api.version}}/vault/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Google Account",
  "resource": "https://accounts.google.com",
  "description": "Personal Google account.",
  "login": "my.email@gmail.com",
  "password": "MyNewSecretPassword789!",
  "collection": {
    "id": 2
  }
}

### Delete a vault item
# @name deleteVaultItem
DELETE {{host}}/{{api.path}}/{{api.version}}/vault/1
Authorization: Bearer {{auth_token}}
