name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  JAVA_VERSION: '23'

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }} with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven            # auto restore/save
          cache-dependency-path: |
            **/pom.xml
            **/.mvn/wrapper/maven-wrapper.properties

      # Optional: prefetch deps to warm cache on cold runs
      - name: Go offline (warm cache)
        run: mvn -B -q -DskipTests dependency:go-offline

      - name: Format check
        run: mvn -B com.spotify.fmt:fmt-maven-plugin:2.25:check

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }} with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
          cache-dependency-path: |
            **/pom.xml
            **/.mvn/wrapper/maven-wrapper.properties

      - name: Run tests with coverage
        run: mvn --batch-mode --update-snapshots test jacoco:report

      - name: Publish unit test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: target/surefire-reports/*.xml
          report_individual_runs: true

      - name: JUnit Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: target/surefire-reports/*.xml
          check_name: JUnit Test Report

      - name: Add coverage to PR
        if: github.event_name == 'pull_request'
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/target/site/jacoco/jacoco.xml,
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: Code Coverage Report
          update-comment: true

      - name: Fail PR if overall coverage is less than 70%
        if: ${{ github.event_name == 'pull_request' && steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed(`Overall coverage is less than 70%! Current coverage: ${process.env.COVERAGE}%`)
        env:
          COVERAGE: ${{ steps.jacoco.outputs.coverage-overall }}

      - name: Add Coverage PR Comment
        if: ${{ github.event_name == 'pull_request' && steps.jacoco.outputs.coverage-overall != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const coverage = parseFloat('${{ steps.jacoco.outputs.coverage-overall }}');
            const changed = parseFloat('${{ steps.jacoco.outputs.coverage-changed-files }}');
            const isPassing = coverage >= 70.0;
            const emoji = isPassing ? '✅' : '❌';
            const comment = `## ${emoji} Coverage Report

            - **Overall Coverage**: ${coverage}% ${isPassing ? '(Passing)' : '(Failing - minimum 70% required)'}
            - **Changed Files Coverage**: ${changed}% ${changed >= 70 ? '✓' : '✗ (minimum 70% required)'}

            ${!isPassing ? '⚠️ **This PR will be blocked until coverage reaches 80%**' : ''}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
